export const CATEGORIAS_FIXAS = [
  "Alvenaria e Argamassa",
  "Impermeabilização",
  "Esquadrias e Vidros",
  "Cobertura e Telhado",
  "Revestimentos e Acabamentos",
  "Pisos e Calçadas",
  "Pintura",
  "Elétrica e Iluminação",
  "Hidráulica e Sanitários",
  "Ar Condicionado e Ventilação",
  "Gás",
  "Estrutura Metálica",
  "Concreto e Formas",
  "Madeiras e Compensados",
  "Ferragens e Fixadores",
  "Ferramentas e EPI",
  "Paisagismo e Urbanização",
  "Demolição e Limpeza",
  "Locação de Equipamentos",
  "Serviços e Mão de Obra",
  "Outros",
] as const;
